spring:
  activemq:
    broker-url: tcp://192.168.94.151:61616
    in-memory: true
    user: admin
    password: admin
    packages:
      trust-all: true
      trusted:
    pool:
      enabled: true  #如果此处设置为true，需要加activemq-pool的依赖包，
      idle-timeout: 3000
      max-connections: 20
      expiry-timeout: 10
  #jms:
   # pub-sub-domain: true